name: guess_who
description: "Guess who? game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  particles_flutter: ^1.0.0
  provider: ^6.1.5
  stomp_dart_client: ^3.0.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/iphone_frame.png
    - assets/bg.jpg
    - assets/main_menu.png
    - assets/main_logo.png

    - assets/icons/default_user.png
    - assets/icons/find_room.png
    - assets/icons/join_submit.png
  fonts:
  - family: BowlbyOneSC
    fonts:
      - asset: fonts/BowlbyOneSC-Regular.ttf






